import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import {
  SettingsSchema,
  isMcpServerCommandEntry,
  isMcpServerNameEntry,
  isMcpServerUrlEntry,
} from '../../../src/utils/settings/types.ts'

const originalEnv = { ...process.env }

function restoreEnv() {
  for (const key of Object.keys(process.env)) {
    if (!(key in originalEnv)) {
      delete process.env[key]
    }
  }
  for (const [key, value] of Object.entries(originalEnv)) {
    if (value === undefined) {
      delete process.env[key]
    } else {
      process.env[key] = value
    }
  }
}

beforeEach(restoreEnv)
afterEach(restoreEnv)

describe('settings types advanced', () => {
  test('parses a broad real-world settings object and normalizes compatibility fields', () => {
    process.env.CLAUDE_CODE_ENABLE_XAA = '1'

    const parsed = SettingsSchema().parse({
      $schema: 'https://json.schemastore.org/claude-code-settings.json',
      apiKeyHelper: '/usr/local/bin/key-helper',
      xaaIdp: {
        issuer: 'https://idp.example.com',
        clientId: 'claude-code',
        callbackPort: 3333,
      },
      fileSuggestion: {
        type: 'command',
        command: 'fd .',
      },
      cleanupPeriodDays: 14,
      attribution: {
        commit: 'Generated by Claude Code',
        pr: 'PR generated by Claude Code',
      },
      permissions: {
        allow: ['Bash(git:*)'],
        additionalDirectories: ['/tmp/workspace'],
      },
      model: 'claude-sonnet-4-6',
      availableModels: ['sonnet', 'claude-sonnet-4-6'],
      modelOverrides: {
        'claude-sonnet-4-6': 'provider/model-id',
      },
      enabledMcpjsonServers: ['github'],
      disabledMcpjsonServers: ['filesystem'],
      hooks: {
        PostToolUse: [
          {
            matcher: 'Edit|Write',
            hooks: [{ type: 'command', command: 'echo done' }],
          },
        ],
      },
      worktree: {
        symlinkDirectories: ['node_modules'],
        sparsePaths: ['packages', 'src'],
      },
      defaultShell: 'bash',
      allowedHttpHookUrls: ['https://hooks.example.com/*'],
      httpHookAllowedEnvVars: ['API_TOKEN'],
      strictPluginOnlyCustomization: ['skills', 'commands', 'hooks'],
      statusLine: {
        type: 'command',
        command: 'echo status',
        padding: 2,
      },
      enabledPlugins: {
        'reviewer@internal-marketplace': true,
        'formatter@internal-marketplace': ['^1.0.0'],
      },
      extraKnownMarketplaces: {
        'internal-marketplace': {
          source: {
            source: 'settings',
            name: 'internal-marketplace',
            plugins: [
              {
                name: 'reviewer',
                source: {
                  source: 'github',
                  repo: 'example/reviewer',
                },
                description: 'Review helper',
              },
            ],
          },
          installLocation: '/tmp/internal-marketplace',
          autoUpdate: true,
        },
      },
      strictKnownMarketplaces: [
        { source: 'github', repo: 'anthropics/claude-code-marketplace' },
        { source: 'hostPattern', hostPattern: '^github\\.example\\.com$' },
      ],
      blockedMarketplaces: [
        { source: 'pathPattern', pathPattern: '^/tmp/unapproved/' },
      ],
      forceLoginMethod: 'claudeai',
      forceLoginOrgUUID: 'org-123',
      otelHeadersHelper: '/usr/local/bin/otel-helper',
      outputStyle: 'compact',
      language: 'japanese',
      feedbackSurveyRate: 0.25,
      spinnerTipsEnabled: true,
      spinnerVerbs: {
        mode: 'append',
        verbs: ['Reviewing', 'Planning'],
      },
      spinnerTipsOverride: {
        excludeDefault: true,
        tips: ['Remember to run tests'],
      },
      syntaxHighlightingDisabled: false,
      terminalTitleFromRename: true,
      alwaysThinkingEnabled: true,
      effortLevel: 'invalid',
      fastMode: true,
      fastModePerSessionOptIn: true,
      promptSuggestionEnabled: false,
      showClearContextOnPlanAccept: true,
      agent: 'reviewer',
      companyAnnouncements: ['Welcome'],
      pluginConfigs: {
        'reviewer@internal-marketplace': {
          mcpServers: {
            github: {
              token: 'abc',
              enabled: true,
              retries: 2,
              scopes: ['repo'],
            },
          },
          options: {
            mode: 'strict',
            enabled: true,
            count: 2,
            tags: ['review'],
          },
        },
      },
      remote: {
        defaultEnvironmentId: 'env-123',
      },
      autoUpdatesChannel: 'stable',
      minimumVersion: '2.0.0',
      plansDirectory: '.claude/plans',
      channelsEnabled: true,
      allowedChannelPlugins: [
        {
          marketplace: 'internal-marketplace',
          plugin: 'reviewer',
        },
      ],
      prefersReducedMotion: true,
      autoMemoryEnabled: true,
      autoMemoryDirectory: '~/.claude/memory',
      autoDreamEnabled: false,
      showThinkingSummaries: true,
      disableAutoMode: 'disable',
      sshConfigs: [
        {
          id: 'prod',
          name: 'Production',
          sshHost: 'deploy@example.com',
          sshPort: 2222,
          sshIdentityFile: '~/.ssh/id_ed25519',
          startDirectory: '~/projects/app',
        },
      ],
      claudeMdExcludes: ['**/generated/CLAUDE.md'],
      pluginTrustMessage: 'Internal plugins are reviewed by security.',
      customTopLevelField: 'preserved',
    })

    expect(parsed.xaaIdp).toEqual({
      issuer: 'https://idp.example.com',
      clientId: 'claude-code',
      callbackPort: 3333,
    })
    expect(parsed.strictPluginOnlyCustomization).toEqual(['skills', 'hooks'])
    expect(parsed.effortLevel).toBeUndefined()
    expect(parsed.extraKnownMarketplaces?.['internal-marketplace']?.source).toMatchObject(
      {
        source: 'settings',
        name: 'internal-marketplace',
      },
    )
    expect(parsed.pluginConfigs?.['reviewer@internal-marketplace']?.options).toEqual(
      {
        mode: 'strict',
        enabled: true,
        count: 2,
        tags: ['review'],
      },
    )
    expect(parsed.sshConfigs?.[0]).toMatchObject({
      id: 'prod',
      sshHost: 'deploy@example.com',
      sshPort: 2222,
    })
    expect((parsed as Record<string, unknown>).customTopLevelField).toBe(
      'preserved',
    )
  })

  test('drops invalid strictPluginOnlyCustomization values instead of failing the whole file', () => {
    const parsed = SettingsSchema().parse({
      strictPluginOnlyCustomization: 'skills',
      hooks: {
        PreToolUse: [
          {
            hooks: [{ type: 'command', command: 'echo ok' }],
          },
        ],
      },
    })

    expect(parsed.strictPluginOnlyCustomization).toBeUndefined()
    expect(parsed.hooks?.PreToolUse).toHaveLength(1)
  })

  test('reports mismatched settings-sourced marketplace names at the nested key path', () => {
    const result = SettingsSchema().safeParse({
      extraKnownMarketplaces: {
        'marketplace-key': {
          source: {
            source: 'settings',
            name: 'different-name',
            plugins: [],
          },
        },
      },
    })

    expect(result.success).toBe(false)
    if (result.success) {
      throw new Error('expected settings validation to fail')
    }

    expect(result.error.issues[0]?.path).toEqual([
      'extraKnownMarketplaces',
      'marketplace-key',
      'source',
      'name',
    ])
    expect(result.error.issues[0]?.message).toContain(
      'Settings-sourced marketplace name must match its extraKnownMarketplaces key',
    )
  })

  test('identifies MCP allow/deny entry variants with the exported type guards', () => {
    const nameEntry = { serverName: 'github' }
    const commandEntry = { serverCommand: ['npx', '@modelcontextprotocol/server'] }
    const urlEntry = { serverUrl: 'https://example.com/*' }

    expect(isMcpServerNameEntry(nameEntry)).toBe(true)
    expect(isMcpServerCommandEntry(nameEntry)).toBe(false)
    expect(isMcpServerUrlEntry(nameEntry)).toBe(false)

    expect(isMcpServerNameEntry(commandEntry)).toBe(false)
    expect(isMcpServerCommandEntry(commandEntry)).toBe(true)
    expect(isMcpServerUrlEntry(commandEntry)).toBe(false)

    expect(isMcpServerNameEntry(urlEntry)).toBe(false)
    expect(isMcpServerCommandEntry(urlEntry)).toBe(false)
    expect(isMcpServerUrlEntry(urlEntry)).toBe(true)
  })
})
